version: '3'
services:
  db:
    image: postgres:10
    container_name: postgres
    restart: always
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=skillschecker
    volumes:
      - "./postgresql/initdb:/docker-entrypoint-initdb.d"
    ports:
      - "5432:5432"
  api:
    build: ../api
    container_name: api
    ports:
      - "3000:3000"
    depends_on:
      - app
  app:
    build: .
    container_name: client
    ports:
      - "80:80"
    depends_on:
      - db
