export const environment = {
  production: true,
  api: {
//  host: 'https://skillscheck.citoproject.eu',
    host: 'https://34.254.132.188',
    port: '',
    path: '/api/'
  },
  readspeaker: {
    enabled: true,
    id: 12420,
    lang: 'en_uk',
    voice: 'Alice'
  },
  product: 'nala',
  locale: 'ie',
  regions: [
    'Online',
    'Carlow',
    'Cavan',
    'Clare',
    'Cork City',
    'Cork County',
    'Donegal',
    'Dublin North',
    'Dublin North County - Fingal',
    'Dublin South',
    'Dublin West County',
    'Dun Laoghaire - Rathdown',
    'Galway',
    'Kerry',
    'Kildare',
    'Kilkenny',
    'Laois',
    'Leitrim',
    'Limerick City',
    'Limerick County',
    'Longford',
    'Louth',
    'Mayo',
    'Meath',
    'Monaghan',
    'Offaly',
    'Roscommon',
    'Sligo',
    'Tipperary',
    'Waterford City',
    'Waterford County',
    'Westmeath',
    'Wexford',
    'Wicklow'
  ]
};
